apiVersion: apps/v1
kind: Deployment
metadata:
  name: certus-music
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: certus-music
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  revisionHistoryLimit: 10
  template:
    metadata:
      labels:
        app: certus-music
        version: "latest"
    spec:
      containers:
      - name: certus-music
        image: jesusmatosdev2020/certusmusic:1.0.0
        imagePullPolicy: name
        envFrom:
            - configMapRef:
                name: certus-music-config
        ports:
         - name: certus-port-1
           containerPort: 3800
           protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: certus-music
spec:
  type: LoadBalancer
  ports:
  - port: 3800
  selector:
    app: certus-music
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: certus-music-config
data:
  MONGO_HOST: 172.168.1.26
  MONGO_DBNAME: certusmusic
  PORT: 3800